/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.consultorach;
import dtos.UsuarioDTO;
import enums.TipoDocumento;
import gestores.GestorCandidato;
import gestores.GestorLDAP;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Vulturius
 */
public class AutenticarCandidato extends javax.swing.JPanel {

    /**
     * Creates new form AutenticarCandidato
     */
    private JFrame ventana;
    private JPanel padre;
    public AutenticarCandidato(JFrame ventana, JPanel padre) {
       this.ventana = ventana;
       this.padre = padre;
       ventana.setTitle("Autenticar usuario - Candidato");
       ventana.setSize(600,450);
       ventana.setVisible(true);
       
        String[] results = new String[TipoDocumento.values().length];
        int i = 0;
        for (TipoDocumento each  : TipoDocumento.values()) {
            results[i] = each.toString();
            
            System.out.println("El valor es: "+results[i]);
            i++;
        }
        List<String> tipos = new ArrayList<>();
        tipos = Arrays.asList(results);
        //lista.addItem(TipoDocumento);
       
       initComponents();
        for(int j=0; j<tipos.size(); j++){
            lista.addItem(tipos.get(j));
        }
        
       this.ventana = ventana;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdni = new javax.swing.JLabel();
        txtnum = new javax.swing.JLabel();
        txtClave = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        textNumero = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtdni.setBackground(new java.awt.Color(255, 255, 255));
        txtdni.setForeground(new java.awt.Color(0, 0, 0));
        txtdni.setText("Tipo de documento");

        txtnum.setBackground(new java.awt.Color(255, 255, 255));
        txtnum.setForeground(new java.awt.Color(0, 0, 0));
        txtnum.setText("Numero de documento");

        txtClave.setBackground(new java.awt.Color(255, 255, 255));
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setText("Clave");

        lista.setBackground(new java.awt.Color(255, 255, 255));
        lista.setForeground(new java.awt.Color(0, 0, 0));

        textNumero.setBackground(new java.awt.Color(255, 255, 255));
        textNumero.setForeground(new java.awt.Color(0, 0, 0));
        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("Iniciar sesion");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        errorMessage.setBackground(new java.awt.Color(255, 255, 255));
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessage)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                            .addComponent(btnSalir))
                        .addComponent(txtClave)
                        .addComponent(txtdni)
                        .addComponent(lista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnum)
                        .addComponent(textNumero)
                        .addComponent(jPasswordField1)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessage)
                .addGap(15, 15, 15)
                .addComponent(txtdni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(btnSalir))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "¿Desea regresar a la pantalla de Autenticar usuario?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        switch(result){
            case JOptionPane.YES_OPTION:
                 ventana.setContentPane(new AutenticarUsuario(ventana, this));
                 break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
        // TODO add your handling code here:
        
       if(textNumero.getText().length() >10 ){
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_textNumeroKeyTyped

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        GestorCandidato gc =  GestorCandidato.getInstance();
        boolean check=false;
        boolean permiso=true;
        check = gc.chequearCamposVacios(textNumero.getText(), String.valueOf(jPasswordField1.getPassword())); 
       
        if(check==false){
            permiso=false;
            jLabel1.setText("Por favor complete ambos campos");
            jLabel1.setVisible(true);
        }else{
            permiso=true; 
            UsuarioDTO dto = new UsuarioDTO();
            dto.setTipoDocumento((String) lista.getSelectedItem());
            System.out.println("EL TIPO ES: "+dto.getTipoDocumento());
            dto.setDocumento(textNumero.getText());
            dto.setClave(String.valueOf(jPasswordField1.getPassword()));
            UsuarioDTO control = gc.autenticarCandidato(dto);
        
           // System.out.println("El candidato es: "+control.getNombre());
           // System.out.println("El cuestionario es: "+control.getCuestionario().getId());
        
       
            if(control.getDocumento()==null && permiso==true){
                permiso=false;
            jLabel1.setText("Los datos ingresados no son validos o no existe un cuestionario para el candidato.");
            jLabel1.setVisible(true);
            }else{
                if(!control.getCuestionario().getEstado().equals("ACTIVO")){
                 JOptionPane.showMessageDialog(this, "El cuestionario esta en proceso.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                }else
                   ventana.setContentPane(new CuestionarioInstrucciones(ventana, this, control));
 
                
             //yyy aca habria que pasarle control que tiene el valor de id del cuestionario
             //del candidato.
        }
        }
        
        
       
    }//GEN-LAST:event_btnInicioActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        char[] pass= jPasswordField1.getPassword();
         jPasswordField1.setEchoChar('*');
         
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
        if(jPasswordField1.getText().length() >8 ){
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_jPasswordField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField textNumero;
    private javax.swing.JLabel txtClave;
    private javax.swing.JLabel txtdni;
    private javax.swing.JLabel txtnum;
    // End of variables declaration//GEN-END:variables
}
