/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.consultorach;

/**
 *
 * @author Vulturius
 */
import com.mycompany.consultorach.entidades.Competencia;
import com.mycompany.consultorach.entidades.Puesto;
import com.mycompany.consultorach.entidades.Puntuacion;
import dtos.CompetenciaDTO;
//import dtos.CompetenciaDTO;
import dtos.PuestoDTO;
import dtos.UsuarioDTO;
import gestores.GestorEvaluacion;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/*import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;*/

public class Evaluacion extends javax.swing.JPanel {

    /**
     * Creates new form Evaluacion
     */
    private JFrame ventana;
    private JPanel padre;
    private List<UsuarioDTO> candidatosDTO;
    private PuestoDTO puestoSeleccionado;
    public Evaluacion(JFrame ventana, JPanel padre, List<UsuarioDTO> candidatos, PuestoDTO puestoSeleccionado) {
       this.ventana = ventana;
       this.padre = padre;
       this.candidatosDTO = candidatos;
       this.puestoSeleccionado = puestoSeleccionado;
      
       ventana.setTitle("Evaluar candidatos - Evaluación");
       ventana.setSize(880,680);
       ventana.setVisible(true);
       initComponents();
       boolean control=false;
       
       Empresa.setVisible(false);
       puesto.setVisible(false);
        codigo.setVisible(false);
       
       if(puestoSeleccionado != null){
        List<Puntuacion> puntuaciones = new ArrayList();
        puntuaciones = puestoSeleccionado.getPuntuaciones();
        DefaultTableModel model = (DefaultTableModel) tabla1.getModel();
        
       for(int j=0; j<puntuaciones.size(); j++){
            model.addRow(new Object[]{puntuaciones.get(j).getCompetencia().getNombre(), puntuaciones.get(j).getPuntajeMinimo()});
        }
        Empresa.setText(puestoSeleccionado.getEmpresa());
       Empresa.setVisible(true);
       puesto.setText(puestoSeleccionado.getNombre());
       puesto.setVisible(true);
       codigo.setText(String.valueOf(puestoSeleccionado.getCodigo()));
       codigo.setVisible(true);
       
        }
       
        
       
       
       
        
        
      DefaultTableModel model2 = (DefaultTableModel) tabla2.getModel();
       for(int i = 0; i<candidatos.size(); i++){
           model2.addRow(new Object[]{candidatos.get(i).getApellido(),candidatos.get(i).getNombre(),candidatos.get(i).getTipoDocumento(),candidatos.get(i).getDocumento(), candidatos.get(i).getClave()});
       }
       
      
       
       this.ventana = ventana;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puestoAEvaluar = new javax.swing.JLabel();
        empresaDelPuesto = new javax.swing.JLabel();
        puestoTitulo = new javax.swing.JLabel();
        Empresa = new javax.swing.JLabel();
        btnBuascarPuesto = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        panelCandidatos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        puesto = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        puestoAEvaluar.setBackground(new java.awt.Color(255, 255, 255));
        puestoAEvaluar.setForeground(new java.awt.Color(0, 0, 0));
        puestoAEvaluar.setText("Puesto a evaluar-Codigo:");

        empresaDelPuesto.setBackground(new java.awt.Color(255, 255, 255));
        empresaDelPuesto.setForeground(new java.awt.Color(0, 0, 0));
        empresaDelPuesto.setText("Empresa: ");

        puestoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        puestoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        puestoTitulo.setText("Puesto: ");

        Empresa.setBackground(new java.awt.Color(255, 255, 255));
        Empresa.setForeground(new java.awt.Color(0, 0, 0));
        Empresa.setText("jLabel6");

        btnBuascarPuesto.setBackground(new java.awt.Color(255, 255, 255));
        btnBuascarPuesto.setForeground(new java.awt.Color(0, 0, 0));
        btnBuascarPuesto.setText("BuscarPuesto");
        btnBuascarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuascarPuestoActionPerformed(evt);
            }
        });

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion de las competencias del puesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelInfo.setForeground(new java.awt.Color(0, 0, 0));

        tabla1.setAutoCreateRowSorter(true);
        tabla1.setBackground(new java.awt.Color(255, 255, 255));
        tabla1.setForeground(new java.awt.Color(0, 0, 0));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Competencia", "Ponderacion"
            }
        ));
        tabla1.setShowHorizontalLines(true);
        tabla1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCandidatos.setBackground(new java.awt.Color(255, 255, 255));
        panelCandidatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidatos a evaluar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelCandidatos.setForeground(new java.awt.Color(0, 0, 0));

        tabla2.setAutoCreateRowSorter(true);
        tabla2.setBackground(new java.awt.Color(255, 255, 255));
        tabla2.setForeground(new java.awt.Color(0, 0, 0));
        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellido", "Nombre", "Tipo documento", "Nro documento", "Clave de ingreso"
            }
        ));
        jScrollPane2.setViewportView(tabla2);

        javax.swing.GroupLayout panelCandidatosLayout = new javax.swing.GroupLayout(panelCandidatos);
        panelCandidatos.setLayout(panelCandidatosLayout);
        panelCandidatosLayout.setHorizontalGroup(
            panelCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCandidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCandidatosLayout.setVerticalGroup(
            panelCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCandidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        puesto.setBackground(new java.awt.Color(255, 255, 255));
        puesto.setForeground(new java.awt.Color(0, 0, 0));
        puesto.setText("jLabel2");

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(empresaDelPuesto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Empresa))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(puestoAEvaluar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(codigo)))
                                .addGap(169, 169, 169)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(puestoTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puesto))
                                    .addComponent(btnBuascarPuesto)))
                            .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(btnFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtras)
                        .addGap(12, 12, 12)
                        .addComponent(btnCancelar)))
                .addGap(15, 19, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoAEvaluar)
                    .addComponent(btnBuascarPuesto)
                    .addComponent(codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresaDelPuesto)
                    .addComponent(Empresa)
                    .addComponent(puestoTitulo)
                    .addComponent(puesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuascarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuascarPuestoActionPerformed
    
        
        // TODO add your handling code here:
      
        
         ventana.setContentPane(new PuestoEvaluar(ventana, this,  candidatosDTO));
    }//GEN-LAST:event_btnBuascarPuestoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
         int result = JOptionPane.showConfirmDialog(this, "¿Desea regresar al Menú Principal?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        switch(result){
            case JOptionPane.YES_OPTION:
                 ventana.setContentPane(new Menu(ventana, this));
                 break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
         int result = JOptionPane.showConfirmDialog(this, "¿Desea regresar a la pantalla de Busqueda de Candidato?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        switch(result){
            case JOptionPane.YES_OPTION:
                 ventana.setContentPane(new BusquedaCandidatos(ventana, this));
                 break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabla1.getModel();
        int filas = model.getRowCount();
        
        if(filas >0){
           
            
         List<Puntuacion> puntuaciones = new ArrayList();
         puntuaciones = puestoSeleccionado.getPuntuaciones();
        
            
            
            GestorEvaluacion GE = GestorEvaluacion.getInstance();
            GE.generarEvaluacion( candidatosDTO, puestoSeleccionado);
            
            
            JOptionPane.showMessageDialog(this, "La evaluacion fue generada con exito", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            
            int result = JOptionPane.showConfirmDialog(this, "¿Desea exportar la lista de candidato a un Excel?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
            switch(result){
                case JOptionPane.YES_OPTION:
                generarExcel();
                 break;
                case JOptionPane.NO_OPTION:
                    ventana.setContentPane(new Menu(ventana, this));
                break;
        }
            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un puesto.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed
    
    public void openFile(String file){
         try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    public void generarExcel(){
         try{
           JFileChooser jFileChooser = new JFileChooser();
           jFileChooser.showSaveDialog(this);
           File saveFile = jFileChooser.getSelectedFile();
           
           if(saveFile != null){
               saveFile = new File(saveFile.toString()+".xlsx");
               Workbook wb = new XSSFWorkbook();
               Sheet sheet =  (Sheet) wb.createSheet("customer");
               
               Row rowCol = sheet.createRow(0);
               for(int i=0;i<tabla2.getColumnCount();i++){
                   Cell cell = rowCol.createCell(i);
                   cell.setCellValue(tabla2.getColumnName(i));
               }
               
               for(int j=0;j<tabla2.getRowCount();j++){
                   Row row = sheet.createRow(j+1);
                   for(int k=0;k<tabla2.getColumnCount();k++){
                       Cell cell = row.createCell(k);
                       if(tabla2.getValueAt(j, k)!=null){
                           cell.setCellValue(tabla2.getValueAt(j, k).toString());
                       }
                   }
               }
               FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
               wb.write(out);
               wb.close();
               out.close();
               openFile(saveFile.toString());
           }else{
               JOptionPane.showMessageDialog(null,"Error al generar archivo");
           }
       }catch(FileNotFoundException e){
           System.out.println(e);
       }catch(IOException io){
           System.out.println(io);
       }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Empresa;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuascarPuesto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel empresaDelPuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelCandidatos;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JLabel puesto;
    private javax.swing.JLabel puestoAEvaluar;
    private javax.swing.JLabel puestoTitulo;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
