package com.mycompany.consultorach;


import dtos.PuestoDTO;
import gestores.GestorCompetencia;
import gestores.GestorPuesto;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vulturius
 */
public class ModificarPuesto extends javax.swing.JPanel {

    /**
     * Creates new form AltaPuesto
     */
    private JFrame ventana;
    private JPanel padre;
    public ModificarPuesto(JFrame ventana, JPanel padre) {
        this.ventana = ventana;
        this.padre = padre;
        ventana.setTitle("Gestionar puestos - Alta puesto");
        ventana.setSize(760, 800);
        initComponents();
        ventana.setVisible(true);
        jTable2.setAutoCreateRowSorter(true);
       
        textDescripcion.setLineWrap(true);
          List<String> nombres = recuperarNombreCompetencias();
    
    for(int i=0;i<nombres.size();i++){
        jComboBox1.addItem(nombres.get(i));
          
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textCodigo = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        textEmpresa = new javax.swing.JTextField();
        empresa = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        competencia = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ponderacion = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        obligatorios = new javax.swing.JLabel();
        etiqueta4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        etiqueta5 = new javax.swing.JLabel();

        textCodigo.setEditable(false);
        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });
        textCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodigoKeyTyped(evt);
            }
        });

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        textNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombreKeyTyped(evt);
            }
        });

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setText("Codigo (*)");

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre (*)");

        textEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmpresaActionPerformed(evt);
            }
        });
        textEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEmpresaKeyTyped(evt);
            }
        });

        empresa.setBackground(new java.awt.Color(255, 255, 255));
        empresa.setText("Empresa (*)");

        descripcion.setBackground(new java.awt.Color(255, 255, 255));
        descripcion.setText("Descripcion (*)");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Caracteristicas (*)"));

        competencia.setBackground(new java.awt.Color(255, 255, 255));
        competencia.setText("Competencia");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jComboBox1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBox1ComponentAdded(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        ponderacion.setBackground(new java.awt.Color(255, 255, 255));
        ponderacion.setText("Ponderacion");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setBackground(new java.awt.Color(255, 255, 255));
        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Competencia", "Ponderacion"
            }
        ));
        jTable2.setShowGrid(true);
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(competencia)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(ponderacion))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitar)
                    .addComponent(btnAgregar)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(competencia)
                        .addGap(47, 47, 47)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ponderacion)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        obligatorios.setBackground(new java.awt.Color(255, 255, 255));
        obligatorios.setText("Campos obligatorios (*)");

        etiqueta4.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta4.setForeground(new java.awt.Color(255, 0, 0));

        textDescripcion.setColumns(20);
        textDescripcion.setRows(5);
        textDescripcion.setWrapStyleWord(true);
        textDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(obligatorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcion)
                                    .addComponent(empresa)
                                    .addComponent(codigo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(96, 96, 96)
                                                .addComponent(nombre)
                                                .addGap(18, 18, 18)
                                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(etiqueta4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(etiqueta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresa))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)
                    .addComponent(obligatorios))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("jLabel2");

        etiqueta5.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta5.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta2)
                            .addComponent(jLabel1)
                            .addComponent(etiqueta3)
                            .addComponent(etiqueta5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(321, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      int result = JOptionPane.showConfirmDialog(this,"¿Desea regresar a la pantalla de Gestionar Puesto?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        switch (result){
            case JOptionPane.YES_OPTION:
            ventana.setContentPane(new GestionarPuesto(ventana, this));
            break;
            case JOptionPane.NO_OPTION:
            break;
        }

    }//GEN-LAST:event_btnCancelarActionPerformed
       

    @SuppressWarnings("empty-statement")
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //int cod = Integer.parseInt(textCodigo.getText());
        jLabel1.setVisible(false);
        etiqueta2.setVisible(false);
        etiqueta3.setVisible(false);
        etiqueta4.setVisible(false);
        etiqueta5.setVisible(false);
         etiqueta2.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta2.setForeground(new java.awt.Color(255, 0, 0));
         etiqueta3.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta3.setForeground(new java.awt.Color(255, 0, 0));
         boolean control=true;
         GestorPuesto gp =  GestorPuesto.getInstance();
     
      
       
         String s1 = textCodigo.getText();
         String s2 = textNombre.getText();
         String s3 = textEmpresa.getText();
         String s4 = textDescripcion.getText();
        int[] mensajes = gp.validarDatos(s1,s2,s3,s4, jTable2);
        if(mensajes[0]==1){
            jLabel1.setText("Por favor complete todos los campos.");
            jLabel1.setVisible(true);
            control=false;
            Toolkit.getDefaultToolkit().beep();
           
        }
        if(mensajes[1] == 1){
            control=false;
            etiqueta3.setText("El campo codigo solo debe contener numeros.");
            etiqueta3.setVisible(true);
             Toolkit.getDefaultToolkit().beep();
        }
        if(mensajes[2] == 1){
             control=false;
            etiqueta4.setText("Los campos nombre y empresa solo pueden contener letras.");
            etiqueta4.setVisible(true);
             Toolkit.getDefaultToolkit().beep();
        }
        if(mensajes[3] == 1){
             control=false;
            etiqueta5.setText("El campo descripcion debe ser alfanumerico.");
            etiqueta5.setVisible(true);
             Toolkit.getDefaultToolkit().beep();
        }
        
         if( mensajes[4]==1){
            etiqueta2.setText("Por favor seleccione una competencia de la lista y ponderacion.");
            etiqueta2.setVisible(true);
        control=false;
        };
           
            if(control==true){
                int result = JOptionPane.showConfirmDialog(this,"¿Desea crear este nuevo puesto?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
        switch (result){
            case JOptionPane.YES_OPTION:
                boolean existePuesto = recuperarDatos();
                if(existePuesto == false){
                    JOptionPane.showMessageDialog(this, "El puesto ya se encuentra registrado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
                else{
            JOptionPane.showMessageDialog(this, "El puesto se ha creado con exito", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            this.textCodigo.setText("");
            this.textNombre.setText("");
            this.textEmpresa.setText("");
            this.textDescripcion.setText("");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            for(int i = model.getRowCount()-1; i>=0; i--){
             model.removeRow(i);
            }
            break;
                }
            case JOptionPane.NO_OPTION:

            break;
        }
            }

    }//GEN-LAST:event_btnAceptarActionPerformed


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        if(jComboBox1.getSelectedItem()=="SELECCIONAR" || jComboBox1.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Seleccione una competencia y una ponderacion", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }else{
           
           ArrayList c = obtenerColumna(jTable2, 0);
           if(c.contains(jComboBox1.getSelectedItem())){
               JOptionPane.showMessageDialog(this, "La competencia ya ha sido seleccionada.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
           }else{
               model.addRow(new Object[]{jComboBox1.getSelectedItem(), jSpinner1.getValue()});
           }
            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        
    }//GEN-LAST:event_textNombreActionPerformed

    private void textEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmpresaActionPerformed
      
    }//GEN-LAST:event_textEmpresaActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        
    }//GEN-LAST:event_textCodigoActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int fila=jTable2.getSelectedRow();
        if(fila >= 0){
            model.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(this, "Debe selecciona una fila para eliminar.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void textNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreKeyTyped
        // TODO add your handling code here:
        char letra= evt.getKeyChar();
        if(Character.isLowerCase(letra)){
            evt.setKeyChar(Character.toUpperCase(letra));
        }
        
         if(textNombre.getText().length() > 50){
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_textNombreKeyTyped

    private void textEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEmpresaKeyTyped
        // TODO add your handling code here:
        char letra= evt.getKeyChar();
        if(Character.isLowerCase(letra)){
            evt.setKeyChar(Character.toUpperCase(letra));
        }
 
        if(textNombre.getText().length() > 50){
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_textEmpresaKeyTyped

    private void textCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoKeyTyped
        // TODO add your handling code here:
        if(textCodigo.getText().length() > 9){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

    }//GEN-LAST:event_textCodigoKeyTyped


    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
   
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseExited

    private void textDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescripcionKeyTyped
        // TODO add your handling code here:
        char letra= evt.getKeyChar();
        if(Character.isLowerCase(letra)){
            evt.setKeyChar(Character.toUpperCase(letra));
        }
 
        if(textDescripcion.getText().length() > 300){
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_textDescripcionKeyTyped

    private void jComboBox1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBox1ComponentAdded
    
 
        
    }//GEN-LAST:event_jComboBox1ComponentAdded

  public List<String> recuperarNombreCompetencias(){
    
    GestorCompetencia gestorC = GestorCompetencia.getInstance();
    return gestorC.recuperarNombreCompetencias();
  
    }  
     private boolean recuperarDatos(){
    GestorPuesto gestorPuesto = GestorPuesto.getInstance();
    ArrayList c= obtenerColumna(jTable2,0);
    ArrayList p= obtenerColumna(jTable2,1);
        PuestoDTO dto = new PuestoDTO();
        dto.setCodigo(Integer.parseInt(textCodigo.getText()));
        dto.setNombre(textNombre.getText());
        dto.setEmpresa(textEmpresa.getText());
        dto.setDescripcion(textDescripcion.getText());
        dto.setCompetencias(c);
        dto.setPuntaje(p);
       // return gestorPuesto.crearPuesto(textCodigo.getText(), textNombre.getText(), textEmpresa.getText(), textDescripcion.getText(), p, c);
        return gestorPuesto.crearPuesto(dto);
        
    }
  public ArrayList obtenerColumna(JTable tabla, Integer a){
       ArrayList columna = new ArrayList();
       DefaultTableModel model = (DefaultTableModel) tabla.getModel();
    for(int i = 0;i<model.getRowCount();i++)
    {   
   columna.add(model.getValueAt(i,a)); //get the all row values at column index 0
   //System.out.println("Las competencias son:" + columna.get(i));
}
return columna;
  }
  
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel competencia;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel empresa;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel etiqueta4;
    private javax.swing.JLabel etiqueta5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel obligatorios;
    private javax.swing.JLabel ponderacion;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textEmpresa;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

}

